; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp8285_sx1280_ranging_sw_master]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/ranging_sw/main.cpp> +<serial_wrapper.cpp>
build_flags = -D RANGING_MASTER

[env:esp8285_sx1280_ranging_sw_slave]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/ranging_sw/main.cpp> +<serial_wrapper.cpp>

[env:esp8285_sx1280_ranging_hw_master]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/ranging_hw/main.cpp>
build_flags = -D RANGING_MASTER

[env:esp8285_sx1280_ranging_hw_slave]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/ranging_hw/main.cpp>

[env:esp8285_sx1280_lora_tx]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/lora/main_tx.cpp>

[env:esp8285_sx1280_lora_rx]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<samples/lora/main_rx.cpp>

[env:esp32_lr1121_lora_wan_tx]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<samples/lora_wan/main_tx.cpp>
build_flags = -DRF_CHIP_LR1121
lib_deps = adafruit/Adafruit NeoPixel@^1.11.0

[env:esp32_sx1276_lora_wan_tx]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<samples/lora_wan/main_tx.cpp>
build_flags = -DRF_CHIP_SX1276
lib_deps = adafruit/Adafruit NeoPixel@^1.11.0
