; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp8285_sx1280_master_ranging]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<main_ranging.cpp>
build_flags = -D RANGING_MASTER

[env:esp8285_sx1280_slave_ranging]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<main_ranging.cpp>

[env:esp8285_sx1280_tx]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<main_tx.cpp>

[env:esp8285_sx1280_rx]
platform = espressif8266
board = esp8285
framework = arduino
build_src_filter = +<main_rx.cpp>

